sculpin_theme:
  theme: broderboy/deadfish
  #theme: sculpin/bootstrap-3-blog-theme

sculpin_content_types:
  posts:
    permalink: :year/:month/:slug_filename.html

jb_tag_cloud:
    tag_permalink: /tags/:taxon/index.html
    tag_entity: Jb\Bundle\TagCloudBundle\Model\Tag
    tag_cloud_entity: Jb\Bundle\TagCloudBundle\Model\TagCloud
    max_number: 0
    strategies:
        - jb_sculpin.tag_cloud.strategy.alpha
        - jb_sculpin.tag_cloud.strategy.percent_size